version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: libary
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  web:
    build: .
    volumes:
      - ./libary:/libary
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgresd@db:5432/libary
      - REDIS_URL=redis://default:redispw@redis:6379
    command: bash -c "sleep 10 && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: on-failure

