# Generated by Django 4.2.6 on 2024-06-10 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tracker", "0004_alter_readerbookrelationship_reader_delete_reader"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tracker.author"
            ),
        ),
        migrations.AlterField(
            model_name="readerbookrelationship",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tracker.book"
            ),
        ),
        migrations.AlterField(
            model_name="readerbookrelationship",
            name="reader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
